owner: dariogriffo
repo: deb-griffo-io-status
sites:
  - name: Debian Package Repository
    url: https://deb.griffo.io/apt/dists/trixie/InRelease
    method: GET
    expectedStatus: 200
status-website:
  cname: status.deb.griffo.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/assets/icon.svg
